name: dr_connect_new_fresh
description: "DR-Connect App."

publish_to: 'none'  # Elimina esta línea si deseas publicarlo en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1  # Firebase Core
  cloud_firestore: ^5.6.5  # Firestore
  firebase_auth: ^5.5.1  # Autenticación de Firebase (si la necesitas)
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  http: ^1.3.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/